const Quiz = require("../models/Quiz");
const QuizResult = require("../models/QuizResult");
const { buildFollowUpQuestions } = require("../utils/followUpQuizGenerator");

function normalizeMissedConcepts(result) {
  // Support multiple possible field names
  const mc =
    result?.missedConcepts ||
    result?.missed_concepts ||
    result?.missedConceptTags ||
    result?.missedTags ||
    [];
  return Array.isArray(mc) ? mc : [];
}

module.exports = {
  // GET /api/quizzes/suggested?userEmail=...
  async getSuggestedQuiz(req, res) {
    try {
      const userEmail = (req.query.userEmail || "").toString().trim().toLowerCase();
      if (!userEmail) return res.status(400).json({ ok: false, error: "userEmail is required" });

      // Find most recent result with missed concepts
      const latest = await QuizResult.findOne({ userEmail }).sort({ createdAt: -1 }).lean();
      if (!latest) {
        return res.json({ ok: true, suggestedQuiz: null, createdFollowUp: false, source: "no_results" });
      }

      const missedConcepts = normalizeMissedConcepts(latest).map(x => String(x).trim()).filter(Boolean);

      if (missedConcepts.length === 0) {
        return res.json({ ok: true, suggestedQuiz: null, createdFollowUp: false, source: "no_missed_concepts" });
      }

      // If an auto-generated follow-up quiz already exists recently, return it
      const existing = await Quiz.findOne({
        generatedForEmail: userEmail,
        isAutoGenerated: true,
        conceptTags: { $in: missedConcepts }
      }).sort({ createdAt: -1 });

      if (existing) {
        return res.json({
          ok: true,
          suggestedQuiz: existing,
          createdFollowUp: false,
          source: "existing_auto_followup"
        });
      }

      // Create a follow-up quiz if none exists
      const questions = buildFollowUpQuestions(missedConcepts);

      // If we can infer courseId from result, attach; else leave null
      const courseId = latest.courseId || null;

      const quizDoc = await Quiz.create({
        title: `Follow-up Quiz: ${missedConcepts[0]}`,
        description: "Auto-generated follow-up based on missed concepts.",
        courseId,
        questions,
        isAutoGenerated: true,
        source: "auto_followup",
        conceptTags: missedConcepts,
        generatedForEmail: userEmail
      });

      return res.json({
        ok: true,
        suggestedQuiz: quizDoc,
        createdFollowUp: true,
        source: "auto_followup"
      });
    } catch (err) {
      return res.status(500).json({ ok: false, error: err.message || "Server error" });
    }
  }
};
