[CmdletBinding()]
param(
  [switch]$DeleteJunk
)

$ErrorActionPreference = "Stop"

function Ensure-LineInFile {
  param(
    [Parameter(Mandatory)] [string]$FilePath,
    [Parameter(Mandatory)] [string]$Line
  )
  if (-not (Test-Path $FilePath)) { New-Item -ItemType File -Path $FilePath -Force | Out-Null }
  $content = Get-Content $FilePath -ErrorAction SilentlyContinue
  if ($content -notcontains $Line) {
    Add-Content -Path $FilePath -Value $Line
  }
}

Write-Host "=== Repo hygiene ===" -ForegroundColor Cyan

# --- 1) Ensure archive folder exists ---
$archiveDir = Join-Path (Get-Location) "_archive"
if (-not (Test-Path $archiveDir)) {
  New-Item -ItemType Directory -Path $archiveDir -Force | Out-Null
  Write-Host "[OK] Created _archive/" -ForegroundColor Green
}

# --- 2) Patch .gitignore (append-only, no dupes) ---
$gitignore = Join-Path (Get-Location) ".gitignore"

$rules = @(
  "# --- generated by scripts/repo-hygiene.ps1 ---",
  "",
  "# Env (never commit real secrets)",
  ".env",
  ".env.*",
  "!.env.example",
  "",
  "# Runtime / secrets artifacts (DO NOT COMMIT)",
  "seed-artifacts.json",
  "seed-artifacts.*.json",
  "smoke-artifacts.json",
  "e2e*.log",
  "*.log",
  "*.out",
  "*.err",
  "server.out.log",
  "server.err.log",
  "build.log",
  "",
  "# Reports",
  "newman-report*.html",
  "newman-report.html",
  "auth-report.html",
  "*.html",
  "",
  "# Backups / archives / quarantine",
  "_archive/",
  "_env_archive/",
  "_quarantine/",
  "_routes_UNUSED/",
  "*_backup*/",
  "*.bak",
  "*.bak-*",
  "*.ps5fix.bak",
  "",
  "# OS / editor",
  ".DS_Store",
  "Thumbs.db",
  ".vscode/",
  ".idea/",
  ""
)

foreach ($r in $rules) {
  Ensure-LineInFile -FilePath $gitignore -Line $r
}

Write-Host "[OK] .gitignore updated" -ForegroundColor Green

# --- 3) Archive clutter safely (without moving _archive into itself) ---
# You can tweak this list. We archive by default; delete only if -DeleteJunk is provided.
$patternsToArchive = @(
  "*.bak",
  "*.bak-*",
  "*.ps5fix.bak",
  "*.log",
  "*.out",
  "*.err",
  "newman-report*.html",
  "newman-report.html",
  "auth-report.html"
)

$items = @()
foreach ($p in $patternsToArchive) {
  $items += Get-ChildItem -Path (Get-Location) -Recurse -File -Filter $p -ErrorAction SilentlyContinue
}

# Exclude anything already inside _archive
$items = $items | Where-Object { $_.FullName -notlike "$archiveDir*" }

if ($items.Count -gt 0) {
  Write-Host "[INFO] Found $($items.Count) junk-ish files to archive" -ForegroundColor Yellow

  foreach ($f in $items) {
    $dest = Join-Path $archiveDir $f.Name
    # Avoid collisions: if file exists, suffix timestamp
    if (Test-Path $dest) {
      $stamp = Get-Date -Format "yyyyMMddHHmmss"
      $dest = Join-Path $archiveDir ($f.BaseName + "." + $stamp + $f.Extension)
    }

    if ($DeleteJunk) {
      Remove-Item -LiteralPath $f.FullName -Force
    } else {
      Move-Item -LiteralPath $f.FullName -Destination $dest -Force
    }
  }

  if ($DeleteJunk) {
    Write-Host "[OK] Deleted junk files (per -DeleteJunk)" -ForegroundColor Green
  } else {
    Write-Host "[OK] Archived junk files into _archive/" -ForegroundColor Green
  }
} else {
  Write-Host "[OK] No junk files found to archive" -ForegroundColor Green
}

# --- 4) Security warning: seed-artifacts.json contains JWTs ---
$seedArtifacts = Join-Path (Get-Location) "seed-artifacts.json"
if (Test-Path $seedArtifacts) {
  Write-Host "[WARN] seed-artifacts.json exists and likely contains JWTs. It should be gitignored + untracked." -ForegroundColor Red
  Write-Host "      If it was ever pushed: rotate JWT_SECRET and re-seed tokens." -ForegroundColor Red
}

Write-Host "=== Done ===" -ForegroundColor Cyan
